site:
  title: 1on1ガイド
  start_page: ROOT::index.adoc
  url: https://guide.1on1guide.org
  robots: allow
  keys:
    google_analytics: 'G-R9M74R2SP8'
content:
  sources: 
  - url: https://github.com/1on1guide-org/1on1meeting-guide.git
    # branches: main
    start_paths: guide
ui: 
  bundle:
    url: https://github.com/1on1guide-org/1on1guide-docs-ui/releases/download/prod-latest/ui-bundle.zip
    snapshot: true
runtime:
  log:
    level: debug
    failure_level: warn
asciidoc:
  sourcemap: true
  attributes:
    page-pagination: ''
    kroki-fetch-diagram: true
  extensions:
  - asciidoctor-kroki
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [ja, en]