site:
  title: 1on1ガイド
  start_page: ROOT::index.adoc
  url: http://localhost:8080
  robots: allow
  keys:
    google_analytics: 'G-123456'
content:
  sources: 
  - url: ~/git/1on1guide-org/1on1meeting-guide/
    branches: main
    start_paths: guide
ui: 
  bundle:
    url: ~/git/1on1guide-docs-ui/build/ui-bundle.zip
    snapshot: true
runtime:
  log:
    level: debug
    failure_level: warn
asciidoc:
  sourcemap: true
  attributes:
    page-pagination: ''
  extensions:
  - asciidoctor-kroki
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [ja, en]

