# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deploy_pages:
        description: 'Deploy to GitHub Pages.'
        required: true
        type: boolean

  workflow_call:
    inputs:
      deploy_pages:
        description: 'Deploy to GitHub Pages.'
        required: true
        type: boolean



# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      timeout-minutes: 1
      uses: actions/checkout@v4
    - name: Install Node.js
      timeout-minutes: 1
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install Antora
      timeout-minutes: 1
      run: npm i antora
    - name: Generate Site
      timeout-minutes: 3
      run: npx antora antora-playbook.yml
    - name: Upload Artifacts
      timeout-minutes: 1
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/site
        retention-days: 1

  # Deploy job since we're just deploying
  deploy:
    if: (inputs.deploy_pages == true) && (github.ref == 'refs/heads/main')
    # Add a dependency to the build job
    needs: build
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        timeout-minutes: 1
        id: deployment
        uses: actions/deploy-pages@v4
